language: python
python:
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install -r requirements.txt
script:
- bandit -r .
- flake8 .
deploy:
  provider: pypi
  user: briggsb
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: WIXqDkaQyt0M3/IIOVNYrzq8QS+/TP6PiUhXCntKZMcVS6rTFh1RcvihXGTSV7GwHCpnu2hUPCju3fyQuZedTV1DSDroxBsf83dylxcqtiuyn+ngdswsp1QTOGdLzxY8y6ZGm4AJWmrTPgsozfFXUudsFhp8MLlgUruNEefA0ennsscgwYkt0KRffU5gPsyjWyBpzhnKJuSyVA7wOucui4p4PQV5+Qd/2/GjRwIFXn2PctbzLISTSClHe63NHpOp87ccONy4T2JlFo9E63tZiHiL2U7pep8mEqjth8YQgRWE9akAyM84hUfodW4ATJsFqpt4X7c9jjoqB4Jm8T0NQfkdAwaOrNKNPrJRXD8s+nS31JS6QXtyO3taSqyukO9GY5MN27CwHclM4U+QbxBPQGl1R6aqS/+apSlhs6XSzGj+fDm7B81b1jHYOXqfSOjEnGmpF1o/Mj+HkX9TvSGSz6YhaSbUTHn7x2Irpm2qBRPk8vpe9YCKhptoiLCcfLIq2OV8lwYjcACyh+04LFhTpL+h8941x468055JPCMawalAwuOAa2DAAquYIG08TvFbn12UZleGzRcQKk2lrO220WLTIzioTocyBnOCcscm2PV7AxECG4iUFXL2oNNsZ5zpz02qIoBSEsUIJyFBgaACzThAoHxes1Y7nC7gj347bU8=
